[package]
authors = ["Archit Bhonsle <abhonsle2000@gmail.com>"]
description = "Linear algebra powered by WebAssembly"
edition = "2018"
keywords = ["linear algebra", "vector", "matrix", "machine learning", "ml"]
license = "Apache-2.0"
name = "arrays-wasm"
repository = "https://github.com/ArchitBhonsle/arrays.wasm"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
start = []
default = ["console_error_panic_hook", "start"]

[dependencies]
console_error_panic_hook = { version = "0.1", optional = true }
csv = "1.1.6"
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3"
ndarray = { version = "0.15", features = ["serde", "rayon", "matrixmultiply-threading"] }
ndarray-csv = "0.5.1"
ndarray-rand = "0.14"
ndarray-stats = "0.5"
paste = { git = "https://github.com/ArchitBhonsle/paste", branch = "cap-uncap" }
rayon = "1.5"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.1"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
wasm-bindgen-futures = "0.4.22"
wasm-bindgen-rayon = "1.0"
web-sys = { version="0.3.53", features = ["File"] }
wee_alloc = { version = "0.4", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
opt-level = 3
